# This file is used by database git proxy (run rake db:proxy to copy 
# database.proxy.yml to database.yml to enable)
#
# The entries here can be regular expressions, designated by the /
# at the beginning and end of the string, or text strings.  Matching
# is done in order listed here and stops on the first match.
#
- /dev/: database/database.dev.yml
- /master/: database/database.dev.yml
- c4c.dev: database/database.c4c.dev.yml
- c4c.staging: database/database.c4c.staging.yml
- c4c.prod: database/database.c4c.prod.yml
