# This file is copied from vendor/plugins/movement_tracker_canada/mappings.yml
#
# Make sure to edit that file, not the one in RAILS_ROOT/config/mappings.yml
#
lib_path: vendor/plugins/movement_tracker_canada/app/models

databases:
  <%= "ciministry_#{RAILS_ENV}" %>: user, person, access, campus, school_year, year_in_school, campus, assignment, assignmentstatus, cim_hrdb_current_address, cim_hrdb_permanent_address, country, title, emerg, gender, region, state, cim_hrdb_admin, cim_hrdb_priv, cim_hrdb_staff, cim_hrdb_person_year, accountadmin_accessgroup, accountadmin_accountadminaccess, accountadmin_accesscategory, accountadmin_accountgroup, accountadmin_language, accountadmin_vieweraccessgroup, site_multilingual_label, month, prc, prcmethod, semester, week, weeklyreport, year, campus_access, cash_transaction, data_type, event, event_admin, field, field_type, field_value, price_rule, price_rule_type, registration, registration_status, scholarship, super_admin

tables:
  user: accountadmin_viewer
  person: cim_hrdb_person
  cim_hrdb_current_address: cim_hrdb_person
  cim_hrdb_permanent_address: cim_hrdb_person
  accountadmin_accessgroup: accountadmin_accessgroup
  accountadmin_accountadminaccess: accountadmin_accountadminaccess
  accountadmin_accesscategory: accountadmin_accesscategory
  accountadmin_accountgroup: accountadmin_accountgroup
  accountadmin_language: accountadmin_language
  accountadmin_vieweraccessgroup: accountadmin_vieweraccessgroup
  access: cim_hrdb_access
  campus: cim_hrdb_campus
  school_year: cim_hrdb_year_in_school
  year_in_school: cim_hrdb_year_in_school
  assignment: cim_hrdb_assignment
  assignmentstatus: cim_hrdb_assignmentstatus
  country: cim_hrdb_country
  title: cim_hrdb_title
  emerg: cim_hrdb_emerg
  gender: cim_hrdb_gender
  region: cim_hrdb_region
  state: cim_hrdb_province
  cim_hrdb_admin: cim_hrdb_admin
  cim_hrdb_priv: cim_hrdb_priv
  cim_hrdb_staff: cim_hrdb_staff
  cim_hrdb_person_year: cim_hrdb_person_year
  site_multilingual_label: site_multilingual_label
  month: cim_stats_month
  prc: cim_stats_prc
  prcmethod: cim_stats_prcmethod
  semester: cim_stats_semester
  week: cim_stats_week
  weeklyreport: cim_stats_weeklyreport
  year: cim_stats_year
  price_rule_type: cim_reg_priceruletypes
  campus_access: cim_reg_campusaccess
  cash_transaction: cim_reg_cashtransaction
  data_type: cim_reg_datatypes
  event: cim_reg_event
  event_admin: cim_reg_eventadmin
  field: cim_reg_fields
  field_type: cim_reg_fieldtypes
  field_value: cim_reg_fieldvalues
  price_rule: cim_reg_pricerules
  registration: cim_reg_registration
  registration_status: cim_reg_status
  scholarship: cim_reg_scholarship
  super_admin: cim_reg_superadmin



# ciministry
#year_in_school:
#  id: year_id
school_year:
  id: year_id
  name: year_desc
  level: year_id
year_in_school:
  id: year_id
  desc: year_desc
assignment:
  id: assignment_id
  status_id: assignmentstatus_id
assignmentstatus:
  id: assignmentstatus_id
  desc: assignmentstatus_desc
  description: assignmentstatus_desc
country:
  id: country_id
  name: country_desc
  country: country_desc
  abbrev: country_shortDesc
  desc: country_desc
  short_desc: country_shortDesc
  iso_code: country_shortDesc
  code: country_shortDesc
  description: country_desc
  short_description: country_shortDesc
emerg:
  id: emerg_id
gender:
  id: gender_id
  desc: gender_desc
  description: gender_desc
region:
  id: region_id
  desc: reg_desc
state:
  id: province_id
  name: province_desc
  abbreviation: province_shortDesc
  abbrev: province_shortDesc
  description: province_desc
  short_description: province_shortDesc
  
# Column Mappings
user:
  id: viewer_id
  user_id: viewer_userID
  last_login: viewer_lastLogin
  username: viewer_userID
  password: viewer_passWord
  is_active: viewer_isActive
  
person:
  id: person_id
  created_at: person_id
  first_name: person_fname
  last_name: person_lname
  middle_name: person_mname
  preferred_name: person_fname
  email: person_email
  address1: person_local_addr
  city: person_local_city
  zip: person_local_pc
  email: person_email
  phone: person_phone
  address: person_addr

campus:
  id: campus_id
  name: campus_desc
  abbrv: campus_shortDesc
  state_id: province_id
  desc: campus_desc
  short_desc: campus_shortDesc
  description: campus_desc
  short_description: campus_shortDesc
  account_group_id: accountgroup_id
  region_id: region_id
  website: campus_website
  facebook_group: campus_facebookgroup
  gcx_namespace: campus_gcxnamespace
  
cim_hrdb_current_address:
  id: person_id
  address1: person_local_addr
  city: person_local_city
  zip: person_local_pc
  phone: person_local_phone
  email: person_email
  alternate_phone: cell_phone
  state_id: province_id
 
cim_hrdb_permanent_address:
  id: person_id
  address1: person_addr
  city: person_city
  zip: person_pc
  phone: person_phone
  email: person_email
  state_id: province_id
 
cim_hrdb_admin:
  id: admin_id

cim_hrdb_priv:
  id: priv_id
  accesslevel: priv_accesslevel
cim_hrdb_staff:
  id: staff_id
cim_hrdb_person_year:
  id: personyear_id

accountadmin_accessgroup:
  id: accessgroup_id
  key: accessgroup_key

accountadmin_accountadminaccess:
  id: accountadminaccess_id
  privilege: accountadminaccess_privilege

accountadmin_accesscategory:
  id: accesscategory_id
  key: accesscategory_key

accountadmin_accountgroup:
  id: accountgroup_id
  key: accountgroup_key
  label_long: accountgroup_label_long

accountadmin_language:
  id: language_id
  key: language_key
  code: language_code

accountadmin_vieweraccessgroup:
  id: vieweraccessgroup_id

access:
  id: access_id

site_multilingual_label:
  id: label_id
  key: label_key
  label: label_label
  moddate: label_moddate

year:
  id: year_id
  description: year_desc

prc:
  id: prc_id
  first_name: prc_firstName
  method_id: prcMethod_id
  witness_name: prc_witnessName
  notes: prc_notes
  date: prc_date
  integrated_believer: prc_7upCompleted

prcmethod:
  id: prcMethod_id
  description: prcMethod_desc

semester:
  id: semester_id
  description: semester_desc
  start_date: semester_startDate

month:
  id: month_id
  description: month_desc
  number: month_number
  calendar_year: month_calendaryear

weeklyreport:
  id: weeklyReport_id
  spiritual_conversations: weeklyReport_1on1SpConv
  gospel_presentations: weeklyReport_1on1GosPres
  holyspirit_presentations: weeklyReport_1on1HsPres
  followup_completed: weeklyReport_7upCompleted
  spiritual_conversations_student: weeklyReport_1on1SpConvStd
  gospel_presentations_student: weeklyReport_1on1GosPresStd
  holyspirt_presentations_student: weeklyReport_1on1HsPresStd
  followup_completed_student: weeklyReport_7upCompletedStd
  cj_video: weeklyReport_cjVideo
  mda: weeklyReport_mda
  other_evmats: weeklyReport_otherEVMats
  rlk: weeklyReport_rlk
  siq: weeklyReport_siq
  notes: weeklyReport_notes

week:
  id: week_id
  end_date: week_endDate


cash_transaction:
  id: cashtransaction_id
  registration_id: reg_id
  staff_name: cashtransaction_staffName
  received: cashtransaction_recd
  amount_paid: cashtransaction_amtPaid
  updated_at: cashtransaction_moddate


data_type:
  id: datatypes_id
  key: datatypes_key
  description: datatypes_desc


event:
  id: event_id
  name: event_name
  desc_brief: event_descBrief
  desc_detail: event_descDetail
  start: event_startDate
  end: event_endDate
  reg_start: event_regStart
  reg_end: event_regEnd
  website: event_website
  email_text: event_emailConfirmText
  price: event_basePrice
  deposit: event_deposit
  email: event_contactEmail
  price_text: event_pricingText
  on_home_page: event_onHomePage
  allow_cash: event_allowCash


event_admin:
  id: eventadmin_id


field:
  id: fields_id
  type_id: fieldtype_id
  description: fields_desc
  priority: fields_priority
  required: fields_reqd
  invalid: fields_invalid
  hidden: fields_hidden
  data_type_id: datatypes_id


field_type:
  id: fieldtypes_id
  description: fieldtypes_desc


field_value:
  id: fieldvalues_id
  field_id: fields_id
  value: fieldvalues_value
  updated_at: fieldvalues_modTime


price_rule:
  id: pricerules_id
  type_id: priceruletypes_id
  description: pricerules_desc
  field_id: fields_id
  value: pricerules_value
  discount: pricerules_discount


price_rule_type:
  id: priceruletypes_id
  description: priceruletypes_desc


registration:
  id: registration_id
  date: registration_date
  confirm_num: registration_confirmNum
  status_id: registration_status
  balance: registration_balance


registration_status:
  id: status_id
  description: status_desc


scholarship:
  id: scholarship_id
  amount: scholarship_amount
  source_account: scholarship_sourceAcct
  source_description: scholarship_sourceDesc


super_admin:
  id: superadmin_id
