<%= 
dbh = "#{RAILS_ROOT}/config/database/database_header.yml"; dbhd = dbh+".default";
file = File.exists?(dbh) ? dbh : dbhd
File.read(file).chomp
%>

development:
  database: utopian_cdm_dev
  <<: *defaults

test:
  database: mh_common_test
  <<: *defaults
